# base image
FROM node:8.11-alpine as node

#RUN apk update
#RUN apk add nginx==1.12.2-r1

RUN apk add --update nginx && rm -rf /var/cache/apk/*

COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/nginx-custom.conf.dev /etc/nginx/conf.d/default.conf

# set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

RUN npm install -g @angular/cli@6.0.0
COPY package.json ./package.json

RUN npm install

EXPOSE 4200

EXPOSE 80

CMD ng serve --host 0.0.0.0 --poll 1000 & nginx -g "daemon off;"