version: '3.5'
services:
 postgres:
  restart: always
  image: postgres:9.6-alpine
  environment:
    - POSTGRES_PASSWORD=${PGPASSWD}
    - PGDATA=/var/lib/postgresql/data/db-files/
  volumes:
    - pgresdb:/var/lib/postgresql/data/
  ports:
   - 5432:5432
 nodedev:
  restart: always
  build : 
     context: ./server     
     dockerfile: Dockerfile.dev
  volumes:
   - ./server:/usr/src/app
  environment:
   - DEV=true
  networks: 
   - bookboat-dev
  ports:
   - 127.0.0.1:3000:3000
   - 127.0.0.1:9229:9229
 clientdev:
  restart: always
  build:
   context: ./client     
   dockerfile: Dockerfile.dev
  ports:
   - 127.0.0.1:4200:4200
   - 127.0.0.1:8080:80
  networks: 
   - bookboat-dev
  volumes:
   - ./client:/usr/src/app
networks: 
 bookboat-dev:
  name: bookboat-dev
volumes:
 pgresdb: